#!/bin/bash
# This script will correctly start the QEWD Container
#
#
# Run this startup script from the '~/qewd-baseline' folder
#  (or whatever you've renamed it) using:
#
#     - with persistence:    ./start_p
#     - without persistence: ./start
#
echo 'Starting qewd container'
docker run -d --name qewd --rm --network qewd-net -p 8080:8080 -v /home/pi/qewd-baseline:/opt/qewd/mapped -v /home/pi/qewd-baseline/yottadb:/root/.yottadb/r1.28_armv7l/g rtweed/qewd-server-rpi
echo 'qewd Container has been started'